### ISSUE TITLE
Create a diff file

### ISSUE THREAD

**Issue by Guekka** [Deltharis/binarydiffwrapper#1]
Hello, 
I am unable to create a diff file. Here is the diff file I created (it's a zip), but it doesn't work. Could you please tell me what I did wrong ? 

[BinaryDiffLog.txt](https://github.com/Deltharis/binarydiffwrapper/files/2303727/BinaryDiffLog.txt)
[Diff file](https://drive.google.com/file/d/1jPJQXmn2Nycv_OwhgyT0Ag31tcQ4a369/view?usp=sharing)

**Comment by Deltharis** [comment]
Ah, it looks like I require there to be "fileToValidate" section in the json config, or else it fails like this. I'll get around to fixing it, and in the meantime as a workaround you can just try "validating" again the file you're patching (or any file you're sure to have like Skyrim.esm). Or possibly just an empty map would work (I didn't test this):

"filesToValidate": {},

**Comment by Guekka** [comment]
Thanks, _"filesToValidate": {},_ worked perfectly. 
By the way, could this tool be used for other files, like meshes or BSA ?
Edit : I tested it on a txt file, and it worked. If it could work for any files, that would be awesome.

**Comment by Deltharis** [comment]
"could be used" - sure, it doesn't care about the type of the file, it just compares ones and zeroes of the files and creates a file that can be used to transform one into the other.

Whether it makes sense though, that's a different question. I'm not sure what the use case could be if the diff file comes out a comparable size to the original. And the bigger .diff file is higher the chance that it contains some copyrighted content within (depends on bsdiff implementation details).

Overall, I'd expect it to work great for text files, ok for meshes (depends if and how they are compressed), and not too well for BSA (which is a compressed archive, which can mean that small change produces wildly different ones and zeroes)

**Comment by Guekka** [comment]
I also did the test for a BSA, and it seemed to work. Thanks for this fantastic tool.
